### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by atian25** [Azard/egg-oauth2-server#1]
非常赞，感谢回馈。

以下是几点建议：
- 配置修改`exports['oauth2-server']` 改为 `exports.oauth2Server`
```js
  exports.oauth2Server = {
    debug: process.env.NODE_ENV !== 'production',
    grants: [ 'password' ],
    model: oauth_model(app),
  };
```

- 插件也修改为
```js
exports.oauth2Server = {
  enable: true,
  package: 'egg-oauth2-server',
};
```

- `model` 不用用户手动初始化，通过 [Loader API](https://eggjs.org/zh-cn/advanced/loader.html#loader-api) 自动加载，可以参考 [egg-sequelize](https://github.com/eggjs/egg-sequelize/blob/4ee7bceac792a308b80a864088f32b739d4653e8/lib/loader.js#L49) 和 [egg-view-nunjucks](https://github.com/eggjs/egg-view-nunjucks/blob/master/lib/environment.js#L57) 的实现

- app.js 里面的 `console.log` 可以改为 `app.coreLogger`，参见 [日志](https://eggjs.org/zh-cn/core/logger.html)

- `debug: process.env.NODE_ENV !== 'production'` 可以考虑直接读取 `app.config.env === 'local'` 做转换
- `agent.js` 没用可以去掉
- `index.js` 也是多余的，你是用了 simple 那个 boilerplate ？应该用 plugin 那个，建议用 `egg-boilerplate-plugin` 重新初始化下，现在看到有不少不需要的代码，如 package.json 的 scripts 等。

**Comment by Azard** [comment]
感谢指导，我也正在学习 egg 的写法，egg 标准化定好确实适合多人开发。
