### ISSUE TITLE
authenticate报错options.headers.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by acodercat** [Azard/egg-oauth2-server#19]
追踪代码发现是ctx.response.headers.hasOwnProperty，hasOwnProperty不是一个函数。但是不知道怎么解决

**Comment by Azard** [comment]
这个问题应该已经 fix 了：https://github.com/Azard/egg-oauth2-server/issues/11
有更详细的信息吗，这个问题不应该在 2.0.4 版本出现。

**Comment by acodercat** [comment]
你的server.js的authenticate函数里面还是用了node-oauth2的Response

**Comment by Azard** [comment]
我知道了，我马上发个 2.0.5 版。

**Comment by acodercat** [comment]
好，谢谢

**Comment by Azard** [comment]
用 2.0.5 试试，已经发版了

**Comment by acodercat** [comment]
可以了，谢谢，建议在下次版本升级的时候把server.js的127行password后面的逗号去掉，有的版本会报错。可以给node-oauth2的作者提下这个问题，让他们更新

**Comment by Azard** [comment]
我已经去掉了，等我补下测试覆盖率再发个版
