### ISSUE TITLE
code模式能给个client端调用的demo吗

### ISSUE THREAD

**Issue by caiya** [Azard/egg-oauth2-server#21]
我把server端这几个方法全部复写完毕了，现在发现不知道客户端怎么去请求调用了，能给个客户端调用的demo吗？

**Comment by Azard** [comment]
流程顺序和 https://oauth2-server.readthedocs.io/en/latest/ 差不多
我最近有空加个 code mode 的 demo

**Comment by caiya** [comment]
demo我写了个，可以参考：https://github.com/caiya/eggjs-oAuth2-server

**Comment by rexleimo** [comment]
@caiya 你这个不行。。 中间价没有写好

**Comment by caiya** [comment]
@rainbowMorelhahahah 中间价，你是说把认证写成中间件？我那个没用中间件模式，只是给了个大致的demo，可以的话自己抽象成中间件就行了
