### ISSUE TITLE
authorize调用报错

### ISSUE THREAD

**Issue by caiya** [Azard/egg-oauth2-server#22]
我在调用authorize进行302 code授权时服务端报错如下：
![image](https://user-images.githubusercontent.com/12036572/34033179-26009b82-e1b4-11e7-9dba-9817cee13100.png)

![image](https://user-images.githubusercontent.com/12036572/34033170-1c588220-e1b4-11e7-8a0e-aab1890cb584.png)

**Comment by caiya** [comment]
![image](https://user-images.githubusercontent.com/12036572/34033263-75c5b12a-e1b4-11e7-9c7d-dca97b7f9f7a.png)

**Comment by Azard** [comment]
这个是因为 `authorize` 没检测不传入参数的情况，我更新到 2.1.1 版本，或者你在 `authorize({})` 传给空的 object

**Comment by caiya** [comment]
@Azard 还有个问题啊，authorize不是get请求吗，怎么还要获取req.body中的username和password？

![image](https://user-images.githubusercontent.com/12036572/34034809-f25840ee-e1ba-11e7-9295-e5cd059415e0.png)

**Comment by caiya** [comment]
@Azard 还请麻烦尽快解决下，急着用这个授权服务，谢谢了，麻烦了

**Comment by Azard** [comment]
这是一个回调，可以覆盖掉：
https://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#authorize-request-response-options-callback

这个模式比较复杂，我找一下我之前的一个项目用了这个 mode 的
这个用 GET 还是 POST 都行

**Comment by caiya** [comment]
更新了之后怎么password模式老是报错：
```js
{
    "error": "invalid_client",
    "error_description": "Invalid client: client is invalid"
}
```

可是实际上同样代码在2.0.6版本都是ok的。。。。

**Comment by Azard** [comment]
你用的是 egg 1.x 还是 2.x ？
egg-oauth2-server  2.0.6 应该对应的是 egg 1.x
egg-oauth2-server  2.1.x 可能不支持 egg 1.x 了（没测试过），适配了 egg 2.0.0

**Comment by caiya** [comment]
我的eggjs是2.0.0
egg-oauth2-server 在2.0.6版本下获取token（password grant）是ok的：
![image](https://user-images.githubusercontent.com/12036572/34035617-8c7770a8-e1bd-11e7-8dbc-06fa9755aaa0.png)

但是在2.1.1版本就报错：
```json
{
    "error": "invalid_client",
    "error_description": "Invalid client: client is invalid"
}
```

**Comment by caiya** [comment]
我要不把我测试项目打包发你，你帮我看下调试下

**Comment by Azard** [comment]
你把 `extend/oauth.js` 发我邮箱

**Comment by caiya** [comment]
发你了，谢谢了

**Comment by caiya** [comment]
@Azard 请问，我这个问题可以解决吗

**Comment by caiya** [comment]
升级到2.1.2，调用authorize报错：
![image](https://user-images.githubusercontent.com/12036572/34088953-c047e45e-e3e7-11e7-8d99-bec7ad6f05dd.png)

![image](https://user-images.githubusercontent.com/12036572/34088935-9e06b12c-e3e7-11e7-8b50-4a59bd94d38a.png)

**Comment by caiya** [comment]
@Azard  哥们，大概啥时候能修复好呢，急着用

**Comment by Azard** [comment]
这个应该是你 handle 函数要返回 user 相关的 object，不然 check 的时候失败

**Comment by caiya** [comment]
@Azard handle函数指的是什么？

**Comment by caiya** [comment]
@Azard 还有楼主，请教下，authorize调用的时候必须输入用户名密码是吗？这一步对应在oAuth里面是不就是：用户已经重定向到认证服务器的登录页，然后点击登录就调用authorize？？

**Comment by caiya** [comment]
这个handle失败貌似是因为getUser返回了空导致的，能不能统一处理下

**Comment by Azard** [comment]
@caiya 这一步可以用这个 oauth2-server 做验证，也可以你自己做好了回调，如果回调的话可以设一个默认的密码，反正只要 oauth2-server 通过就行。
getUser 返回为空，是因为 token 里没有给 user 赋值吧。

**Comment by caiya** [comment]
@Azard 已经解决了，完整的demo我也写好了

**Comment by Azard** [comment]
@caiya 好滴，有时间可以提交个这个 mode 的 test case 给其他人参考下

**Comment by caiya** [comment]
@Azard 怎么设置accesstoken的过期时长呢

**Comment by Azard** [comment]
@caiya `token. accessTokenExpiresAt` 这个值自行设置一下，new Date() 加上你的有效时间。

**Comment by caiya** [comment]
@Azard  理解了，是不就是这样子


![image](https://user-images.githubusercontent.com/12036572/34248525-6c937d28-e671-11e7-9d5a-a5b98b458230.png)

**Comment by Azard** [comment]
是这样的

**Comment by Java-http** [comment]
> 我的eggjs是2.0.0
> egg-oauth2-server 在2.0.6版本下获取token（password grant）是ok的：
> ![image](https://user-images.githubusercontent.com/12036572/34035617-8c7770a8-e1bd-11e7-8dbc-06fa9755aaa0.png)
> 
> 但是在2.1.1版本就报错：
> 
> ```json
> {
>     "error": "invalid_client",
>     "error_description": "Invalid client: client is invalid"
> }
> ```

你好，当时你这个问题是怎么解决的，可否提供下解决方法，谢谢
