### ISSUE TITLE
传入fresh_token获取新的access_token问题

### ISSUE THREAD

**Issue by heimi-block** [Azard/egg-oauth2-server#26]
1.路由要怎么写才能触发到这个传入fresh_token获取新的access_token
2.路由要怎么写能调用到revokeToken()

**Comment by heimi-block** [comment]
module.exports = app => {  
  class Model {
    constructor (ctx) {
      this.ctx = ctx
    }
    async getClient(clientId, clientSecret) {
      const client = {
        clientId: 'my_app',
        clientSecret: 'my_secret',
        grants: [ 'password' ]
      }
      if (clientId !== client.clientId || clientSecret !== client.clientSecret) {
        return
      }
      return client
    }

    async getUser(username, password) {
      const user = await app.model.User.findOne({mobile: username})
      if(!user){
        return 
      }
      const result = await this.ctx.compare(password, user.password)
      if(!result){
        return
      }
      return { userId: user._id }
    }

    async getAccessToken(bearerToken) {
      const token = await app.model.OauthToken.findOne({accessToken: bearerToken})
      if(!token){
        return
      }
      const { userId, clientId } = token
      const user = await app.model.User.findById(userId)
      token.user = user
      token.accessTokenExpiresAt = new Date(token.accessTokenExpiresAt)
      token.refreshTokenExpiresAt = new Date(token.refreshTokenExpiresAt)
      return token
    }

    async saveToken(token, client, user) {      
      const _token = Object.assign({}, token, { userId: user.userId || user.id }, { clientId: client.clientId })
      await app.model.OauthToken(_token).save()
      _token.client = client
      _token.user = user
      return _token
    }
    async revokeToken(token) {
      await app.model.OauthToken.remove({refreshToken: token.refreshToken})
    }
  }  
  return Model
}

**Comment by heimi-block** [comment]
// 路由
`  router.get('/api/user', app.oAuth2Server.authenticate(), controller.user.fetchAll)
  router.put('/api/user/:id', controller.user.update)

  // oauth
  app.all('/user/token', app.oAuth2Server.token())`

想知道路由这里这么写**app.oAuth2Server.xxx**,可以触发传入fresh_token获取新的access_token,
我试着把调用app.oAuth2Server.token()，修改了提交的内容，grant_type: refresh_token， 同时去掉传入username和password，header传入refresh token，但返回invalid grant_type！！
请教一下开发者，这里如何命名方法才可实现

**Comment by heimi-block** [comment]
module.exports = app => {
  const mongoose = app.mongoose
  
  const OauthTokenSchema = new mongoose.Schema({
    accessToken: { type: String },
    accessTokenExpiresAt: { type: Date },
    refreshToken:  { type: String },
    refreshTokenExpiresAt: { type: Date },
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    clientId: { type: String },
    createdAt: { type: Date, default: Date.now }
  })

  return mongoose.model('OauthToken', OauthTokenSchema)
}

**Comment by heimi-block** [comment]
{
    "_id" : ObjectId("5a3dbe3f622d7c391daa9f58"),
    "accessToken" : "a582611b3ee5c65b6b1f2ea836b0781a7fe1ad52",
    "accessTokenExpiresAt" : ISODate("2017-12-23T19:11:59.581Z"),
    "refreshToken" : "cdd5bffaadfb1b72e3fd68386531b52195362fba",
    "refreshTokenExpiresAt" : ISODate("2018-01-06T02:23:59.581Z"),
    "userId" : ObjectId("5a3db2c55c0ddc37af36249f"),
    "clientId" : "my_app",
    "createdAt" : ISODate("2017-12-23T02:23:59.583Z"),
    "__v" : 0
}

**Comment by Azard** [comment]
`grant_type: refresh_token` 是错误的。
`grant_type` 是指你所使用的 oauth2 模式，只有 `password` `authorization_code` 这几种。
`revokeToken` 是一个 egg-oauth2-server 的生命周期函数，可以作为 egg router 的一个执行函数。

**Comment by heimi-block** [comment]
@Azard 开发者您好，感谢您的回答。 
我还有不明白的地方
1.传入fresh_token获取新的access_token我们插件没有封装吗？或者我如何触发调用
2.revokeToken 是一个 egg-oauth2-server 的生命周期函数，可以作为 egg router 的一个执行函数。
我需要自己写controller,通过app.什么能调用到这个revokeToken()方法

**Comment by Azard** [comment]
详细的文档可以看看：
https://oauth2-server.readthedocs.io/en/latest/model/overview.html 
https://oauth2-server.readthedocs.io/en/latest/model/spec.html#model-revoketoken
我这个相当于对它做了上层封装。
1. 我之前回答有误，`refresh_token` 是一个 grant_type，已经封装了的。之前报 invalid grant_type 可能是这个 refresh_token 的部分生命周期没有实现的原因。
一共有4种 grant type：
* authorization_code grant
* client_credentials grant
* refresh_token grant
* password grant
2. API 手动调用 `revokeToken()` 是个不太规范的做法，不过能满足实际需求就好，我觉得不用太教条。 `revokenToken()` 按照规范是在 refresh_token 的生命周期里把之前的 token 回收的步骤。

**Comment by heimi-block** [comment]
@Azard 感谢，
1.对于第一个问题 您说已经封装了，我现在就是不知道通过app.oAuth2Server.什么名字可以触发到我在extend/oauth.js里写的refresh_token做个方法

**Comment by Azard** [comment]
对外的话，按照规范，一共只有3个接口：
https://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#
你都试一下，我也没具体用过 refresh_token 这个 grant_type。

这里是 refresh_token grant_type 的生命周期：
https://oauth2-server.readthedocs.io/en/latest/model/overview.html#refresh-token-grant

egg-oauth2-server 的封装不会改变 oauth2-server 的行为，都是直传的，所以不存在某个 grant_type 没有封装的情况。

**Comment by heimi-block** [comment]
@Azard 感谢您的指点。之间一直用jwt，现在还egg刚好看到您有封装这个方法 实在不行其实不刷新也可，设置时间过期时间长一些 基本能满足我的业务啦 感谢

**Comment by rexleimo** [comment]
其实怎么调用 refreshToken 方法

**Comment by rexleimo** [comment]
@Azard refreshToken 这个发现怎么调用 然后刷新 AccessToken

**Comment by Azard** [comment]
@rainbowMorelhahahah 参考 https://oauth2-server.readthedocs.io/en/latest/
