### ISSUE TITLE
pluginName(oauth2Server) is different from pluginConfigName(oauth2-server)

### ISSUE THREAD

**Issue by caoer** [Azard/egg-oauth2-server#3]
got a warning saying the name is different from plugin config name. logs attached below

```
 [egg:loader] pluginName(oauth2Server) is different from pluginConfigName(oauth2-server)
```

**Comment by Azard** [comment]
Reference: https://github.com/Azard/egg-oauth2-server/tree/master/test/fixtures/apps/oauth2-server-test, plugin and config name use `oauth2Server` .

**Comment by caoer** [comment]
Hi, I'm only seeing config name, in: https://github.com/Azard/egg-oauth2-server/blob/master/test/fixtures/apps/oauth2-server-test/config/config.unittest.js

not seeing a plugin.js. where is the pluginConfigName defined?

**Comment by Azard** [comment]
It's only need to add in egg `App` structure, the unit test for egg `Plugin` not have a `plugin.js` .
Create a new file name `plugin.js` in `{app_root}/config/plugin.js` .
```javascript
// {app_root}/config/plugin.js
exports.oauth2Server = {
  enable: true,
  package: 'egg-oauth2-server',
};
```

**Comment by caoer** [comment]
yep, I'm doing exactly the same, but still seeing the warning.
Can it be related to the number '2' in oauth2Server, which causing the issue?

**Comment by Azard** [comment]
It's really a warning problem, I have fix it with new name `oauth2Server` in package.json `eggPlugin.name` , the project name needn't change.
Use 1.1.0, the warning disappear.

**Comment by caoer** [comment]
👍
