### ISSUE TITLE
replaceResponse

### ISSUE THREAD

**Issue by sm2017** [Azard/egg-oauth2-server#34]
What `replaceResponse` do exactly?
https://github.com/Azard/egg-oauth2-server/blob/master/lib/server.js#L15-L31

Why we cannot do simply ` const response = new Response(ctx.response);` instead of ` const response = new Response(replaceResponse(ctx.response));` ?

**Comment by Azard** [comment]
As the comment say
```
// copy for response.headers.hasOwnProperty is undefined case
// https://github.com/oauthjs/node-oauth2-server/pull/486
```
