### ISSUE TITLE
Is implicit grant mode supported?

### ISSUE THREAD

**Issue by LEAFERx** [Azard/egg-oauth2-server#36]
node-oauth2-server support implicit grant mode now, so is this plugin supported? BTW, if I want to use more than one mode, how do I define the router?

**Comment by Azard** [comment]
The plugin dependency `"oauth2-server": "^3.0.0"` , maybe need update to support new mode.
Multi-mode could using different API for different router entry, reference https://github.com/Azard/egg-oauth2-server#examples

**Comment by LEAFERx** [comment]
Would you please update the plugin？

**Comment by Azard** [comment]
@LEAFERx I have time to maintain this plugin now, could you send me the details about  `implicit grant mode` in https://github.com/oauthjs/node-oauth2-server ?
