### ISSUE TITLE
鉴权之后，如何在 controlle r里面获取用户 ID

### ISSUE THREAD

**Issue by morelearn1990** [Azard/egg-oauth2-server#45]
大神您好，鉴权之后，如何在 controlle r 里面获取用户 ID 呀？

**Comment by morelearn1990** [comment]
想到该怎么做了，直接获取 headers 里面的token值，直接到数据库里面去查一把。但是每个请求都这样做一遍就很恼火，需要找个地方封装起来方便调用

**Comment by Azard** [comment]
可以在 oauth.js 里写到 ctx 里

**Comment by morelearn1990** [comment]
嗯嗯，我后来写到utils的扩展里了，需要的时候直接调用
