### ISSUE TITLE
有关token方法过期时间设置问题

### ISSUE THREAD

**Issue by taxliang** [Azard/egg-oauth2-server#49]
设置accessTokenLifetime refreshTokenLifetime 时区差个小时，如何处理

**Comment by Azard** [comment]
看系统的时区，有必要的话配置里加一个时区修正的配置？

**Comment by taxliang** [comment]
从目前情况看，应该是node默认时区问题。最好能加个时区修正的配置，因为token过期时间参数目前传入的是个整数，不方便调整。
