### ISSUE TITLE
authorization-code有没有这种方式的简单例子

### ISSUE THREAD

**Issue by liuliangjia** [Azard/egg-oauth2-server#5]
authorization-code

有没有这种方式的简单例子？

实在看不明白服务端怎么配置和客户端怎么配合。

**Comment by Azard** [comment]
https://cnodejs.org/topic/592b2aedba8670562a40f60b
这个里面有 authorization_code 的样例，配置也可以参考下这个插件源码里的测试。

**Comment by liuliangjia** [comment]
// {app_root}/config/config.default.js
exports.oauth2Server = {
  grants: [ 'password', 'client_credentials' ],
};

这篇帖子里介绍的是这两种比较简单的认证方式，好像并没有提到authorization_code的样例，我不晓得客户端是怎么样来配合这个，实现第一次拿code，第二次拿授权的流程的？

**Comment by Azard** [comment]
详细的在这里：https://www.npmjs.com/package/node-oauth2-server
`Required for authorization_code grant type` 和 `redirectUri` 这几个应该是相关的。

**Comment by Azard** [comment]
老哥，可以用帮忙加个 star
