### ISSUE TITLE
the ctx of Model can't be changed

### ISSUE THREAD

**Issue by rise0chen** [Azard/egg-oauth2-server#50]
this.ctx can't be changed on each request after constructed.

``` js
module.exports = (app) => {
  class Model {
    constructor(ctx) {
      this.ctx = ctx;
    }
    test() {
      console.log(this.ctx.request.query);
    }
  }
  return Model;
};
````

**Comment by rise0chen** [comment]
hello

**Comment by Azard** [comment]
I'm not get the point

**Comment by rise0chen** [comment]
Adding `console.log(this.ctx.request.query);` to function `getClient(clientId, clientSecret)`   in `app/extend/oauth.js`.  
It will return same content in every authorize request.

**Comment by rise0chen** [comment]
it will through error if having query in `redirect_url` of client.  
for example,if `redirect_url` of client is `domain.cn/xxx`,it will through error when  `redirect_url` is `domain.cn/xxx?xxx` in authorize request. 

so,I want to deal with the problem by change `redirect_url`.
so, I want to get `ctx.request.query` but it don't change in every authorize request.

**Comment by rise0chen** [comment]
#53 
可以在`app/extend/oauth.js`中使用this.x.ctx获取变化后的新ctx。望采纳

**Comment by rise0chen** [comment]
get `ctx` by `app.oAuth2Server.ctx`
