### ISSUE TITLE
关于 model 的讨论

### ISSUE THREAD

**Issue by atian25** [Azard/egg-oauth2-server#6]
## 目前的设计方式
- 用户在 `app/extend/oauth.js` 中提供策略
- 插件会在 app.js 中调用 loadFile

遇到问题：
- oauth.js 一般都会调用 service 进行存储，目前的方式无法支持
- oauth.js 的 API 都是 callback 方式的，不优雅

### 主插件 `egg-oauth2-server` 

职责：
  - 类似 egg-view 和 egg-passport，提供统一的约定和挂载方式
  - 提供 `app.oauth2Server.use(StrategyClass)`
    - `use` 里面可以调用 `loadToContext` 等把 class 注册到 ctx
  - 提供 `app.oauth2Server.Strategy` 基类
    - interface 设计都改为 promise 或 generator 类

### 用户使用方式

```js
// {app_root}/app.js
module.exports = app => {
  const Strategy = require('./lib/oauth2_strategy');
  app.oauth2Server.use(Strategy);
}

// {app_root}/lib/oauth2_strategy.js
module.exports = app => {
  return class MyStrategy extends app.oauth2Server.Strategy {
    constructor(ctx) {
      super(ctx);
    }

    * getAccessToken() {
      return yield ctx.service.xxx();
    }
  }
}
```

### 进一步扩展

- 上面的 `oauth2_strategy.js` 可以独立为二级插件的方式
- 即根据不同的业务场景，封装 `egg-oauth2-server-firebase` / `egg-oauth2-server-alibaba`
- 应用开发者直接安装主插件和二级插件，然后在 `app.js` 中 `use` 下即可

```js
// {app_root}/app.js
module.exports = app => {
  const Strategy = require('./lib/oauth2_strategy');
  app.oauth2Server.use(Strategy);
}

// {app_root}/lib/oauth2_strategy.js
module.exports = app => {
  return class MyStrategy extends app.oauth2Server.Strategy {
    constructor(ctx) {
      super(ctx);
    }

    * getAccessToken() {
      return yield ctx.service.xxx();
    }
  }
}
```

**Comment by atian25** [comment]
可以看下 egg-core 的源码， service 的加载那里用到了 `loadToContext`，用它很容易可以扩展自己的 `ctx.model` / `ctx.db`

**Comment by Azard** [comment]
LGTM，我最近研究下

**Comment by atian25** [comment]
想了下，不需要用 `loadToContext` 了。

```js
const STRATEGY = Symbol('context#oauth2Server');

module.exports = {
  get oauth2Server() {
    if (!this[STRATEGY]) {
      this[STRATEGY] = new this.app.oauth2Server.strategy(this);
    }
    return this[STRATEGY];
  }
}

// use as

yield ctx.oauth2Server.getAccessToken();
```
