### ISSUE TITLE
PR. 根据 oauth2-server 3.x 更新依赖 & 支持 model 调用 ctx

### ISSUE THREAD

**Issue by thonatos** [Azard/egg-oauth2-server#7]
RT.

- 根据 oauth2-server 3.x 配置 model
- 修改 koa-oauth-server 2.x（延迟初始化 oauth2-server）

参考：
- https://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html
- https://oauth2-server.readthedocs.io/en/latest/misc/migrating-v2-to-v3.html

（已经提交PR，代码见分支）

**Comment by thonatos** [comment]
😀  如果没什么问题，我提一个正式的PR #8 .

**Comment by Azard** [comment]
可以呀，原来这个出了新版本。
我过几天会按照 https://github.com/Azard/egg-oauth2-server/issues/6 重新包装下

**Comment by thonatos** [comment]
#6 类比的是 passport，但 oauth server 是服务提供者， 好像分离子插件意义不大的样子~

**Comment by Azard** [comment]
land https://github.com/Azard/egg-oauth2-server/commit/8db48f9c24590d7e5f300c566aa94b1444947a9d
